<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHoyY6Sh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHoyY6Sh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHoyY6Sh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHoyY6Sh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHoyY6Sh\App_KernelDevDebugContainer([
    'container.build_hash' => 'HoyY6Sh',
    'container.build_id' => '87249083',
    'container.build_time' => 1722089819,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHoyY6Sh');
