<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUsNfEMi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUsNfEMi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUsNfEMi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUsNfEMi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUsNfEMi\App_KernelDevDebugContainer([
    'container.build_hash' => 'UsNfEMi',
    'container.build_id' => '2c65771a',
    'container.build_time' => 1722094572,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUsNfEMi');
